"use client";

import { useState } from "react";

const covers = [10000, 20000, 30000, 40000, 50000];
type FormState = { family:boolean; funeral:boolean; data:boolean; first:string; last:string; gender:string; dob:string; id:string; phone:string; email:string; beneficiary:string; relationship:string; payment:"bill"|"debit"; bank:string; account:string; debitDate:string };
const initial:FormState = { family:false,funeral:false,data:false,first:"Jonathan",last:"Smith",gender:"Male",dob:"1994-07-31",id:"9407315209087",phone:"082 555 5555",email:"j.smith@gmail.com",beneficiary:"",relationship:"Spouse",payment:"debit",bank:"",account:"",debitDate:"25" };

function Logo(){return <div className="brand"><span>∞</span><b>vodasure</b><i/><strong>funeral cover</strong></div>}
function Input({label,value,onChange,type="text",placeholder}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>}
function Progress({stage}:{stage:number}){return <div className="progress-wrap"><p>Apply for cover</p><div className="progress">{["Personal details","Add beneficiary","Payment"].map((x,i)=><div className={"progress-step "+(i<stage?"done ":"")+(i===stage?"active":"")} key={x}><span>{i<stage?"✓":""}</span><small>{i===stage?`STEP ${i+1}`:i<stage?"View":""}</small><b>{x}</b></div>)}</div></div>}
function QuoteProgress({step}:{step:number}){return <div className="quote-progress"><p>Get your funeral cover quote</p><div>{["Choose cover","Add benefits","Review quote"].map((x,i)=><span className={i<=step?"active":""} key={x}><i>{i<step?"✓":i+1}</i><b>{x}</b></span>)}</div></div>}
function Actions({back,next,nextText="Continue",backText="Back"}:{back?:()=>void;next:()=>void;nextText?:string;backText?:string}){return <footer className="actions">{back?<button className="btn secondary" onClick={back}>{backText}</button>:<span/>}<button className="btn primary" onClick={next}>{nextText}</button></footer>}
function Card({title,subtitle,success,children}:{title:string;subtitle?:string;success?:boolean;children:React.ReactNode}){return <div className={"card "+(success?"success":"")}>{success&&<div className="success-icon">✓</div>}<header><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</header><div className="card-body">{children}</div></div>}
function Premium({total,base,addons,detailed=false}:{total:number;base:number;addons:number;detailed?:boolean}){return <div className="premium">{detailed&&<><div className="row muted"><span>Cover premium</span><b>R{base.toFixed(2)}</b></div><div className="row muted"><span>Add-on benefit</span><b>R{addons.toFixed(2)}</b></div></>}<div className="row"><strong>Total monthly premium</strong><div><b>R{total.toFixed(2)}</b><del>R120.00</del></div></div></div>}
function Benefit({title,price,active,onClick,icon,children}:{title:string;price:string;active:boolean;onClick:()=>void;icon:string;children:React.ReactNode}){return <article className={"benefit "+(active?"active":"")}><header><span>{icon}</span><b>{title}</b></header><strong>From {price} per month</strong><ul>{children}</ul><button className="learn">Learn more ›</button><button className="benefit-btn" onClick={onClick}>{active?"Benefit added ✓":"Add benefit ＋"}</button></article>}
function Choice({active,onClick,icon,title,text}:{active:boolean;onClick:()=>void;icon:string;title:string;text:string}){return <button className={"choice "+(active?"active":"")} onClick={onClick}><span>{icon}</span><div><b>{title}</b><small>{text}</small></div></button>}

export default function Home(){
  const [step,setStep]=useState(0),[coverIndex,setCoverIndex]=useState(1),[form,setForm]=useState<FormState>(initial);
  const set=<K extends keyof FormState>(k:K,v:FormState[K])=>setForm(f=>({...f,[k]:v}));
  const cover=covers[coverIndex],base=48+coverIndex*24,addons=(form.funeral?10:0)+(form.data?3.75:0),total=base+addons,fullName=`${form.first} ${form.last}`.trim();
  const next=()=>setStep(s=>Math.min(8,s+1)),back=()=>setStep(s=>Math.max(0,s-1)),quoting=step<=2,stage=step<4?0:step<5?1:2;
  return <main className="application-site">
    <header className="application-header"><Logo/></header>
    {quoting?<QuoteProgress step={step}/>:<Progress stage={stage}/>}
    <section className={quoting?"drawer drawer-full":`page step-${step}`} aria-live="polite">
      {step===0&&<><header className="drawer-title"><h1>Get Funeral Cover in minutes</h1><button aria-label="Close">×</button></header><div className="drawer-content">
        <div className="grid two"><Input label="Add your date of birth" type="date" value={form.dob} onChange={v=>set("dob",v)}/><Input label="What’s your cellphone number?" value={form.phone} onChange={v=>set("phone",v)}/></div>
        <h2>Do you want to add family members?</h2><div className="segmented"><button className={!form.family?"selected":""} onClick={()=>set("family",false)}>No</button><button className={form.family?"selected":""} onClick={()=>set("family",true)}>Yes</button></div>
        <h2>Set your cover amount</h2><div className="cover-value">R{cover.toLocaleString("en-ZA")}</div><input className="range" aria-label="Cover amount" type="range" min="0" max="4" value={coverIndex} onChange={e=>setCoverIndex(Number(e.target.value))}/><div className="range-labels">{covers.map(v=><span key={v}>R{v/1000} 000</span>)}</div>
      </div><div className="drawer-footer"><Premium total={base} base={base} addons={0}/><Actions back={()=>setStep(0)} next={next}/></div></>}
      {step===1&&<><header className="drawer-title"><h1>Add extra benefits</h1><button onClick={()=>setStep(0)}>×</button></header><div className="drawer-content"><p className="lead">Congratulations! You qualify for the benefits below</p><div className="benefit-grid">
        <Benefit title="Funeral Assistance" price="R10.00" active={form.funeral} onClick={()=>set("funeral",!form.funeral)} icon="◆"><li>Body Repatriation</li><li>Vouchers to assist with funeral expenses</li><li>Emergency helpline and counselling</li></Benefit>
        <Benefit title="250MB Data Reward" price="R3.75" active={form.data} onClick={()=>set("data",!form.data)} icon="●"><li>Discounted monthly data benefits</li><li>250MB valid for 14 days</li></Benefit>
      </div></div><div className="drawer-footer"><Premium total={total} base={base} addons={addons}/><Actions back={back} next={next}/></div></>}
      {step===2&&<><header className="drawer-title"><h1>Your funeral cover quote</h1><button onClick={()=>setStep(0)}>×</button></header><div className="drawer-content quote-summary"><div className="summary-card centered"><small>Your cover amount</small><strong>R{cover.toLocaleString("en-ZA")}</strong></div><button className="add-family">⊕<span>{form.family?"Family included":"Add family"}</span></button><div className="summary-card"><div className="row"><span>Benefit add-ons</span><span>✎</span></div>{form.funeral&&<div className="row muted"><span>Funeral Assistance</span><b>R10.00</b></div>}{form.data&&<div className="row muted"><span>VodaPay Data Reward</span><b>R3.75</b></div>}{!addons&&<p className="muted">No extra benefits selected</p>}</div></div><div className="drawer-footer"><Premium total={total} base={base} addons={addons} detailed/><label className="terms"><input type="checkbox" defaultChecked/> By selecting ‘Accept quote’ you agree to the <u>Terms and Conditions.</u></label><Actions back={back} next={next} nextText="Accept quote"/></div></>}
      {step===3&&<><div className="page-title"><h1>Personal details</h1></div><Card title="Add personal information"><div className="grid two"><Input label="First name" value={form.first} onChange={v=>set("first",v)}/><Input label="Last name" value={form.last} onChange={v=>set("last",v)}/><Select label="Gender" value={form.gender} onChange={v=>set("gender",v)}><option>Male</option><option>Female</option><option>Prefer not to say</option></Select><Input label="Date of birth" type="date" value={form.dob} onChange={v=>set("dob",v)}/><div className="span-two"><Input label="ID number" value={form.id} onChange={v=>set("id",v)}/><small className="hint">● &nbsp; Your ID number is protected</small></div><Input label="Cellphone number" value={form.phone} onChange={v=>set("phone",v)}/><Input label="Email address" type="email" value={form.email} onChange={v=>set("email",v)}/></div></Card><Actions back={back} next={next} nextText="Confirm"/></>}
      {step===4&&<><div className="page-title center"><h1>Add beneficiary</h1></div><Card title="It’s easy to add a beneficiary"><p>To avoid delays in paying out claims, ensure that all beneficiary details are updated and correct.</p><h3>What you need to add a beneficiary</h3><p className="check">● &nbsp; Beneficiary ID number</p><p className="check">● &nbsp; Beneficiary contact details</p><hr/><h3>Your beneficiary</h3><div className="grid two"><Input label="Full name" placeholder="Beneficiary name" value={form.beneficiary} onChange={v=>set("beneficiary",v)}/><Select label="Relationship" value={form.relationship} onChange={v=>set("relationship",v)}><option>Spouse</option><option>Parent</option><option>Child</option><option>Other</option></Select></div><div className="info">ⓘ &nbsp; You can update your beneficiary details at any time.</div></Card><Actions back={back} next={next} nextText="Add beneficiary"/></>}
      {step===5&&<><div className="page-title center"><h1>Payment</h1></div><Card title="Select payment method" subtitle="How would you like to pay for your cover?"><Choice active={form.payment==="bill"} onClick={()=>set("payment","bill")} icon="▤" title="Add to Vodacom bill" text="The amount will be added to your Vodacom bill at the end of each month"/><Choice active={form.payment==="debit"} onClick={()=>set("payment","debit")} icon="▭" title="Debit order" text="The amount will be deducted from your bank account at the end of each month"/><div className="secure">♙<br/>Secure checkout</div></Card><Actions back={back} next={next}/></>}
      {step===6&&<><div className="page-title center"><h1>Payment</h1></div><Card title="Debit order details" subtitle="Add your banking details to create a monthly debit order"><div className="grid two"><Input label="Account holder name" value={fullName} onChange={()=>{}}/><Select label="Select bank" value={form.bank} onChange={v=>set("bank",v)}><option value="">- Select -</option><option>ABSA</option><option>Capitec</option><option>FNB</option><option>Nedbank</option><option>Standard Bank</option></Select><Input label="Account number" value={form.account} placeholder="Enter account number" onChange={v=>set("account",v)}/><Select label="Account type" value="Cheque" onChange={()=>{}}><option>Cheque</option><option>Savings</option></Select><div className="span-two"><Select label="Debit order date" value={form.debitDate} onChange={v=>set("debitDate",v)}><option value="25">25th of the month</option><option value="1">1st of the month</option><option value="15">15th of the month</option></Select></div></div><h3>When would you like your cover to start?</h3><div className="radio-row"><label>This month <input type="radio" name="start" defaultChecked/></label><label>Next month <input type="radio" name="start"/></label></div></Card><Actions back={back} next={next}/></>}
      {step===7&&<><div className="page-title center"><h1>Payment</h1></div><Card title="Payment summary" subtitle="Monthly premium to cover your life only"><div className="cover-banner">♙ <b>{form.family?"Family":"Individual"} Funeral Cover</b></div><Summary name={fullName} form={form} cover={cover} base={base} addons={addons} total={total}/></Card><Actions back={back} next={next} nextText="Confirm"/></>}
      {step===8&&<><Card success title="Successful application!" subtitle="Your details are submitted! We will send you an SMS and email confirmation shortly."><p className="center-text">Please double check your policy documents when we send them.</p><div className="receipt"><div className="row"><b>Date and time:</b><span>14 Aug 2026 | 10:30</span></div><div className="row"><b>Payment method:</b><span>{form.payment==="debit"?"Debit order":"Vodacom bill"}</span></div><div className="row"><b>Total monthly premium:</b><span>R {total.toFixed(2)}</span></div><hr/><div className="row"><b>Product:</b><span>VodaSure | Funeral cover</span></div><div className="row"><b>Cover amount:</b><span>R {cover.toLocaleString("en-ZA")}</span></div><div className="row"><b>Full name:</b><span>{fullName}</span></div><div className="row"><b>Cellphone number:</b><span>{form.phone}</span></div></div><div className="callout">☎ &nbsp; <b>Call 082 178 00</b><small>For policy-related queries, please contact us immediately.</small></div></Card><Actions next={()=>{setStep(0);setForm(initial)}} nextText="Done"/></>}
    </section>
  </main>
}

function Summary({name,form,cover,base,addons,total}:{name:string;form:FormState;cover:number;base:number;addons:number;total:number}){return <div className="summary-rows"><div className="row"><b>Full name:</b><span>{name}</span></div><div className="row"><b>Cellphone number:</b><span>{form.phone}</span></div><div className="row"><b>Email address:</b><span>{form.email}</span></div><div className="row"><b>Payment method:</b><span>{form.payment==="debit"?"Debit order":"Vodacom bill"}</span></div><hr/><div className="row"><b>Your cover:</b><strong>R {cover.toLocaleString("en-ZA")}</strong></div><div className="row"><b>Monthly premium:</b><strong>R {base.toFixed(2)}</strong></div>{addons>0&&<div className="row"><b>Monthly add-ons:</b><strong>R {addons.toFixed(2)}</strong></div>}<hr/><div className="row total-row"><b>Total monthly premium:</b><strong>R {total.toFixed(2)}</strong></div></div>}
